//
//  main.cpp
//  FibranacciSequenceEvens
//
//  Created by Michael Wienands on 9/22/17.
//  Copyright © 2017 Michael Wienands. All rights reserved.
//
//https://github.com/mwienands/EvenFibonacciNumbers.git
//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-
//valued terms.

#include <iostream>

int main(int argc, const char * argv[]) {
    
    int a = 0;
    int b = 1;
    
    int fib = 0;
    int count = 0;
    
    while(a<4000000){
        fib = a +b;
        a = b;
        b= fib;
        
        if(fib%2==0){
            count += fib;
        }
        
    }
    
    
    
    std::cout << count;
    return 0;
}


